### PR TITLE
Added feature Register as a Validator

### PR DESCRIPTION
**Pull request by wakqasahmed**
* Register as a validator button
* View to select all services to become a validator
* Disable the service checkbox that a user is already validator of
* Submit Register validation request
* Filter self from validators list
* Show incoming requests on home page
* Show incoming requests tab on Requests page (a bit buggy - WIP)

### CODE REVIEW

**Comment by kpachhai** [comment]
Some feedback:
- I don't think the final design from @mfaizanatiq has been integrated here. Can we please do that?

Because from what I remember, the design for how validation services are displayed was a dropdown menu.

**Comment by wakqasahmed** [comment]
Yeah, i agree. The functionality was growing quite large so I just created a separate issue for the homepage redesign to focus independently. Will surely work on it tomorrow.

https://github.com/tuum-tech/vouch-capsule/issues/85

**Comment by kpachhai** [comment]
If that's the case, I can merge this first?

**Comment by kpachhai** [comment]
merged.

**Pull request merged**
